INSERT INTO products(name, proteins, fats, carbohydrates, kcal)
VALUES ('Белые свежие', 3.3, 1.5, 2.4, 32);
INSERT INTO products(name, proteins, fats, carbohydrates, kcal)
VALUES ('Белые сушенные', 23.8, 6.8, 30.2, 277);
INSERT INTO products(name, proteins, fats, carbohydrates, kcal)
VALUES ('Вешенки свежие', 2.5, 0.5, 6.2, 34);
INSERT INTO products(name, proteins, fats, carbohydrates, kcal)
VALUES ('Лисички свежие', 1.5, 1.0, 2.4, 22);
INSERT INTO products(name, proteins, fats, carbohydrates, kcal)
VALUES ('Лисички сушенные', 22.0, 7.2, 25.4, 268);
INSERT INTO products(name, proteins, fats, carbohydrates, kcal)
VALUES ('Маслята свежие', 2.5, 0.7, 1.5, 12);
INSERT INTO products(name, proteins, fats, carbohydrates, kcal)
VALUES ('Опята свежие', 2.4, 1.0, 2.5, 25);
INSERT INTO products(name, proteins, fats, carbohydrates, kcal)
VALUES ('Подберезовики свежие', 2.1, 1.2, 3.4, 30);
INSERT INTO products(name, proteins, fats, carbohydrates, kcal)
VALUES ('Подберезовики сушенные', 23.3, 9.5, 14.4, 231);
INSERT INTO products(name, proteins, fats, carbohydrates, kcal)
VALUES ('Подосиновики свежие', 3.3, 0.4, 3.5, 31);
INSERT INTO products(name, proteins, fats, carbohydrates, kcal)
VALUES ('Подосиновики сушенные', 35.2, 5.4, 33, 325);
INSERT INTO products(name, proteins, fats, carbohydrates, kcal)
VALUES ('Рыжики свежие', 1.9, 0.7, 2.3, 16);
INSERT INTO products(name, proteins, fats, carbohydrates, kcal)
VALUES ('Сыроежки свежие', 1.6, 0.8, 1.7, 15);
INSERT INTO products(name, proteins, fats, carbohydrates, kcal)
VALUES ('Шампиньоны свежие', 4.3, 0.9, 1.4, 29);