INSERT INTO products(name, proteins, fats, carbohydrates, kcal)
VALUES ('Гречневая каша', 4.5, 1.6, 27.4, 137);
INSERT INTO products(name, proteins, fats, carbohydrates, kcal)
VALUES ('Кукурузыне хлопья', 6.5, 2.9, 83.8, 372);
INSERT INTO products(name, proteins, fats, carbohydrates, kcal)
VALUES ('Манная каша', 2.5, 0.3, 16.4, 77);
INSERT INTO products(name, proteins, fats, carbohydrates, kcal)
VALUES ('Овсяная каша', 3.2, 1.8, 15.4, 93);
INSERT INTO products(name, proteins, fats, carbohydrates, kcal)
VALUES ('Овсяные хлопья', 13.9, 7.5, 69.1, 358);
INSERT INTO products(name, proteins, fats, carbohydrates, kcal)
VALUES ('Перловая каша', 3.2, 0.5, 22.7, 102);
INSERT INTO products(name, proteins, fats, carbohydrates, kcal)
VALUES ('Пшеничная каша', 3, 0.8, 17.2, 92);
INSERT INTO products(name, proteins, fats, carbohydrates, kcal)
VALUES ('Рисовая каша', 1.5, 0.2, 17.3, 79);
INSERT INTO products(name, proteins, fats, carbohydrates, kcal)
VALUES ('Ячневая каша', 1.4, 0.3, 18.7, 84);
INSERT INTO products(name, proteins, fats, carbohydrates, kcal)
VALUES ('Ячневые хлопья', 9.1, 3.2, 79.7, 354);